"""Seed products for Operator's Choice store."""
from datetime import datetime, timezone, timedelta

# Curated product imagery (dark, tactical, streetwear aesthetic)
IMG = {
    "hoodie_black": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=1200&q=80",
    "hoodie_olive": "https://images.unsplash.com/photo-1611691543849-9f37b3c4ea88?w=1200&q=80",
    "hoodie_grey": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=1200&q=80",
    "hoodie_red": "https://images.unsplash.com/photo-1586897414837-468be47328c4?w=1200&q=80",
    "tee_black": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=1200&q=80",
    "tee_white": "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=1200&q=80",
    "tee_olive": "https://images.unsplash.com/photo-1622445275576-721325763afe?w=1200&q=80",
    "tee_oversized": "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=1200&q=80",
    "cargo_black": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=1200&q=80",
    "cargo_khaki": "https://images.unsplash.com/photo-1552902875-9ac1f9fe0c07?w=1200&q=80",
    "cargo_olive": "https://images.unsplash.com/photo-1473966968600-fa801b3a09ba?w=1200&q=80",
    "cap_black": "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=1200&q=80",
    "cap_camo": "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=1200&q=80",
    "belt": "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=1200&q=80",
    "patch": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1200&q=80",
    "model1": "https://images.unsplash.com/photo-1579883180654-695b7f038d4c?w=1400&q=80",
    "model2": "https://images.pexels.com/photos/3933967/pexels-photo-3933967.jpeg?w=1400",
    "model3": "https://images.pexels.com/photos/15553981/pexels-photo-15553981.jpeg?w=1400",
    "model4": "https://images.unsplash.com/photo-1618924250456-0c7d405f2d53?w=1400&q=80",
}

DROP_END = (datetime.now(timezone.utc) + timedelta(days=5, hours=11)).isoformat()

PRODUCTS = [
    {
        "slug": "xiii-kargil-oversized-tee",
        "name": "XIII Kargil Oversized Tee",
        "description": "Tribute to the XIII Kargil regiment. Heavyweight 240 GSM cotton, drop-shoulder cut, screen-printed military insignia on chest and full-back graphic. Built for those who carry the legacy.",
        "price": 1499, "compare_at_price": 1999,
        "category": "tees", "collection": "kargil",
        "images": [IMG["tee_oversized"], IMG["model1"], IMG["tee_black"], IMG["model2"]],
        "colors": [{"name": "Matte Black", "hex": "#0A0A0A"}, {"name": "Olive", "hex": "#354026"}],
        "stock": 47, "badges": ["Limited Edition", "Bestseller"],
        "is_new_drop": True, "drop_ends_at": DROP_END,
        "specs": {"Fabric": "240 GSM Cotton", "Fit": "Oversized Drop-Shoulder", "Print": "Plastisol Screen Print", "Origin": "India"},
        "sold_count": 312, "rating": 4.9,
    },
    {
        "slug": "bravest-of-the-brave-hoodie",
        "name": "Bravest of the Brave Hoodie",
        "description": "Heavyweight 400 GSM brushed-back fleece hoodie with embroidered chest crest and minimalist back print. Olive drab with metallic gold accents.",
        "price": 2999, "compare_at_price": 3799,
        "category": "hoodies", "collection": "bravest",
        "images": [IMG["hoodie_olive"], IMG["hoodie_black"], IMG["model3"], IMG["hoodie_grey"]],
        "colors": [{"name": "Olive", "hex": "#354026"}, {"name": "Matte Black", "hex": "#0A0A0A"}, {"name": "Charcoal", "hex": "#2D2D2D"}],
        "stock": 28, "badges": ["Limited Edition"],
        "specs": {"Fabric": "400 GSM Brushed Fleece", "Fit": "Relaxed", "Detail": "Embroidered Crest", "Origin": "India"},
        "sold_count": 198, "rating": 4.8,
    },
    {
        "slug": "operator-tactical-cargo",
        "name": "Operator Tactical Cargo Pant",
        "description": "Mission-ready cargo with reinforced knees, double stitching, hidden pocket layout, and tapered ankle. Made for the operator who never quits.",
        "price": 3499, "compare_at_price": 4499,
        "category": "cargo", "collection": "operator",
        "images": [IMG["cargo_black"], IMG["cargo_khaki"], IMG["cargo_olive"]],
        "colors": [{"name": "Matte Black", "hex": "#0A0A0A"}, {"name": "Khaki", "hex": "#C3B091"}, {"name": "Olive", "hex": "#354026"}],
        "stock": 41, "badges": ["Bestseller"],
        "specs": {"Fabric": "Ripstop Cotton-Poly", "Fit": "Tapered Tactical", "Pockets": "8 (4 cargo, 4 std)", "Origin": "India"},
        "sold_count": 267, "rating": 4.7,
    },
    {
        "slug": "forged-for-the-fearless-tee",
        "name": "Forged for the Fearless Tee",
        "description": "The signature flag-bearer of the brand. Premium 220 GSM combed cotton with high-density chest print. Subtle. Strong. Statement.",
        "price": 1299, "compare_at_price": 1699,
        "category": "tees", "collection": "fearless",
        "images": [IMG["tee_black"], IMG["model1"], IMG["tee_white"]],
        "colors": [{"name": "Matte Black", "hex": "#0A0A0A"}, {"name": "White", "hex": "#FFFFFF"}],
        "stock": 84, "badges": ["Bestseller"],
        "specs": {"Fabric": "220 GSM Combed Cotton", "Fit": "Regular", "Print": "High-Density", "Origin": "India"},
        "sold_count": 521, "rating": 4.9,
    },
    {
        "slug": "patriot-zip-hoodie",
        "name": "Patriot Zip-Up Hoodie",
        "description": "Full-zip hoodie inspired by parade dress codes. Charcoal grey with tonal embroidery, ribbed cuffs, and a stealth interior pocket.",
        "price": 2799, "compare_at_price": 3499,
        "category": "hoodies", "collection": "patriot",
        "images": [IMG["hoodie_grey"], IMG["hoodie_black"], IMG["model4"]],
        "colors": [{"name": "Charcoal", "hex": "#2D2D2D"}, {"name": "Matte Black", "hex": "#0A0A0A"}],
        "stock": 36, "badges": [],
        "specs": {"Fabric": "380 GSM French Terry", "Fit": "Regular", "Detail": "YKK Zip", "Origin": "India"},
        "sold_count": 142, "rating": 4.6,
    },
    {
        "slug": "ghost-protocol-cargo",
        "name": "Ghost Protocol Cargo",
        "description": "Slim-fit cargo with stealth-black hardware and seam-taped pockets. The silent operator's choice.",
        "price": 3299, "compare_at_price": 3999,
        "category": "cargo", "collection": "operator",
        "images": [IMG["cargo_olive"], IMG["cargo_black"]],
        "colors": [{"name": "Olive", "hex": "#354026"}, {"name": "Matte Black", "hex": "#0A0A0A"}],
        "stock": 22, "badges": ["Limited Edition"],
        "specs": {"Fabric": "Stretch Ripstop", "Fit": "Slim Tactical", "Pockets": "6", "Origin": "India"},
        "sold_count": 89, "rating": 4.7,
    },
    {
        "slug": "tactical-flex-cap",
        "name": "Tactical Flex Cap",
        "description": "Low-profile six-panel cap with hook-and-loop patch panel. Wear your own callsign.",
        "price": 899, "compare_at_price": 1199,
        "category": "caps", "collection": "operator",
        "images": [IMG["cap_black"], IMG["cap_camo"]],
        "colors": [{"name": "Matte Black", "hex": "#0A0A0A"}, {"name": "Camo", "hex": "#4B5320"}],
        "sizes": ["One Size"],
        "stock": 120, "badges": ["Bestseller"],
        "specs": {"Material": "Cotton Twill", "Fit": "Adjustable", "Origin": "India"},
        "sold_count": 412, "rating": 4.8,
    },
    {
        "slug": "kargil-victory-tee",
        "name": "Kargil Victory Tee",
        "description": "Heritage piece honoring the 1999 victory. Stone-washed black with vintage-feel print and ribbon-tag detail.",
        "price": 1399, "compare_at_price": 1799,
        "category": "tees", "collection": "kargil",
        "images": [IMG["tee_black"], IMG["model2"]],
        "colors": [{"name": "Stone Black", "hex": "#1A1A1A"}],
        "stock": 55, "badges": ["Limited Edition"],
        "specs": {"Fabric": "240 GSM Cotton", "Fit": "Boxy", "Wash": "Stone", "Origin": "India"},
        "sold_count": 178, "rating": 4.8,
    },
    {
        "slug": "best-of-friends-tee",
        "name": "Best of Friends Tee",
        "description": "From the 'Best of Friends, Worst of Enemies' capsule. Bold dual-tone print across the back.",
        "price": 1599, "compare_at_price": 1999,
        "category": "tees", "collection": "fearless",
        "images": [IMG["tee_olive"], IMG["model3"]],
        "colors": [{"name": "Olive", "hex": "#354026"}, {"name": "Matte Black", "hex": "#0A0A0A"}],
        "stock": 30, "badges": ["One Time Drop"],
        "is_new_drop": True, "drop_ends_at": DROP_END,
        "specs": {"Fabric": "220 GSM Cotton", "Fit": "Regular", "Origin": "India"},
        "sold_count": 64, "rating": 4.7,
    },
    {
        "slug": "regiment-belt",
        "name": "Regiment Tactical Belt",
        "description": "Heavy-duty woven belt with brushed steel buckle. Built to outlast missions.",
        "price": 999, "compare_at_price": 1299,
        "category": "accessories", "collection": "operator",
        "images": [IMG["belt"]],
        "colors": [{"name": "Matte Black", "hex": "#0A0A0A"}, {"name": "Olive", "hex": "#354026"}],
        "sizes": ["One Size"],
        "stock": 200, "badges": [],
        "specs": {"Material": "Nylon Webbing + Steel", "Length": "120cm", "Origin": "India"},
        "sold_count": 233, "rating": 4.6,
    },
    {
        "slug": "morale-patch-set",
        "name": "Morale Patch Set (4 Pieces)",
        "description": "Hook-and-loop morale patch set including 'Forged', 'XIII', 'Operator', and brand crest.",
        "price": 599, "compare_at_price": 799,
        "category": "accessories", "collection": "operator",
        "images": [IMG["patch"]],
        "sizes": ["One Size"],
        "stock": 300, "badges": ["Bestseller"],
        "specs": {"Material": "Embroidered Twill", "Backing": "Hook Velcro", "Origin": "India"},
        "sold_count": 612, "rating": 4.9,
    },
    {
        "slug": "fearless-premium-tee",
        "name": "Fearless Premium Tee",
        "description": "Refined elevation of the Fearless line — heavier fabric, slimmer cut, gold-foil chest mark.",
        "price": 1799, "compare_at_price": 2299,
        "category": "tees", "collection": "fearless",
        "images": [IMG["tee_white"], IMG["model1"]],
        "colors": [{"name": "White", "hex": "#FFFFFF"}, {"name": "Matte Black", "hex": "#0A0A0A"}],
        "stock": 60, "badges": [],
        "specs": {"Fabric": "260 GSM Combed Cotton", "Fit": "Slim", "Print": "Gold Foil", "Origin": "India"},
        "sold_count": 96, "rating": 4.8,
    },
]


COUPONS = [
    {"code": "FORGED10", "description": "Flat 10% off", "discount_type": "percent", "value": 10, "min_order": 999, "active": True},
    {"code": "OPERATOR20", "description": "20% off on orders above ₹2999", "discount_type": "percent", "value": 20, "min_order": 2999, "active": True},
    {"code": "FREESHIP", "description": "₹100 shipping waiver", "discount_type": "flat", "value": 100, "min_order": 0, "active": True},
]

REVIEW_TEMPLATES = [
    ("Arjun M.", 5, "Solid quality. Fabric feels premium and fit is exactly as described. Will buy again."),
    ("Vikram S.", 5, "The print quality is insane. Looks even better in person. 10/10."),
    ("Rohit K.", 4, "Great hoodie. Wish there was a slightly slimmer fit option."),
    ("Sanjana R.", 5, "Boyfriend loved it. Packaging was also next-level."),
    ("Major (Retd.) P.", 5, "Wore it on a 12km ruck — held up perfectly. Brand gets it right."),
]
